### ISSUE TITLE
Error occured when creating bean 'RetrofitAutoConfiguration'

### ISSUE THREAD

**Issue by byWeaponLin** [syhily/spring-boot-retrofit-support#1]
hello, as the title said,and the short log is below.
![error](https://user-images.githubusercontent.com/21023273/30013903-e353f0b4-917b-11e7-9ae0-148258746f5e.png)

This is full log.
[autoconfiguration.txt](https://github.com/syhily/spring-boot-retrofit-support/files/1273796/autoconfiguration.txt)

And this is my project address. [ `lts-cycle-mission` ](https://github.com/byWeaponLin/lts-cycle-mission)

**Comment by syhily** [comment]
Bump your spring boot & spring framework version.

**Comment by byWeaponLin** [comment]
It works now,thank you so much. 
I have no words to response.  π_π
